<a href="https://colab.research.google.com/github/HawraaML/python_tutorial/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**



1.   Introduction

1.   create a vector & array

1.   shape and reshape

1.   Indexing

1.   Slicing

1.   Data type

2.   Array iteration

2.   join

2.   split

2.   search

1.   sort

2.   Universal functions (ufunc)
           - Arithmetic
           - Statistical Functions
           - Rounding



 **NumPy** : is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
!pip install numpy

In [13]:
import numpy as np

In [4]:
print(np.__version__)

1.23.5


In [5]:
vector = ([1,2,3,4])
vector

[1, 2, 3, 4]

In [6]:
# vector of zeros
vector0 = np.zeros(10)
vector0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# vector of ones
vector1 = np.ones(12)
vector1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# vector with range of elements
vector = np.arange(1,10)
vector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# vector of range of elements with steps arange(start,end,step)
vector = np.arange(1,10,2)
vector

array([1, 3, 5, 7, 9])

In [10]:
# 2D array (matrix)
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 3D array (matrix)
arr3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
# creating array with random value
arr = np.random.rand(5,3)
print(arr)

[[0.41901675 0.22568112 0.22926429]
 [0.66542709 0.83681199 0.27089096]
 [0.95607925 0.69179077 0.55864208]
 [0.38461243 0.47321415 0.89136079]
 [0.26001168 0.60704226 0.82089021]]


In [12]:
# to know the number of dimention of array we use ndim
arr1 = np.zeros(10)
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]]])

print("arr1",arr1.ndim)
print("arr2",arr2.ndim)
print("arr3",arr3.ndim)

arr1 1
arr2 2
arr3 3


# **Shape & Reshape**

In [14]:
# shape use to give us the dimention of array
arr1= np.array([[1,2,3],
               [3,4,5],
               [6,7,9]])
arr1.shape

(3, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
arr3.shape

(2, 2, 3)

# Reshape use to convert the dimention of array LIKE 1D to 2D or 3D and vise versa


In [15]:
# from 1D to 2D
arr = np.arange(1,20,2)
print("the array :", arr,"\n")
arr1 = arr.reshape(5,2)
print("the array after reshape :\n", arr1)

the array : [ 1  3  5  7  9 11 13 15 17 19] 

the array after reshape :
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [18]:
# from 1D to 3D
arr = np.arange(1,20,2)
print("the array :", arr,"\n")
arr1 = arr.reshape(1,2,5)
print("the array after reshape :\n", arr1)

the array : [ 1  3  5  7  9 11 13 15 17 19] 

the array after reshape :
 [[[ 1  3  5  7  9]
  [11 13 15 17 19]]]


In [19]:
# convert from 2D to 1D
arr = np.array([[1,2,3],[4,5,6]])
print("the array: \n", arr,"\n")
arr1 = arr.reshape(-1)
print("the array after reshape :\n", arr1)

the array: 
 [[1 2 3]
 [4 5 6]] 

the array after reshape :
 [1 2 3 4 5 6]


# Indexing & slicing

In [20]:
# access element by its index 1D
arr = np.arange(1,10)
print(arr)
print(arr[3])

[1 2 3 4 5 6 7 8 9]
4


In [21]:
# access element by its index 2D
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
6


In [24]:
# access element by its index 3D
arr = np.array([[[1,2,3],[4,5,6]],[[8,9,0],[10,26,15]]])
print(arr)
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9  0]
  [10 26 15]]]
15


In [25]:
# slicing 1D arry[start:end:step]
arr = np.arange(1,10)
print(arr)
print(arr[1:5:3])

[1 2 3 4 5 6 7 8 9]
[2 5]


In [30]:
# slicing 2D arry[start:end:step]
arr = np.array([[1,2,3,7,8,9],[4,5,6,10,11,12],[13,45,67,6,21,88]])
print(arr)
print(arr[0:3:2,0:3])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]
 [13 45 67  6 21 88]]
[[ 1  2  3]
 [13 45 67]]


# Data type


1.   int8, int16, int32, int64 - signed integer types with different bit sizes.

2.   uint8, uint16, uint32, uint64 - unsigned integer types with
different bit sizes

1.   float32, float64 - floating-point types with different precision levels
2.   complex64, complex128 - complex number types with different precision levels









In [31]:
# to know data type of an array we use dtype()
arr = np.arange(20)
print(arr.dtype)

int64


In [32]:
arr = np.array(["hg","ca","na"])
print(arr.dtype)

<U2


In [33]:
arr = np.array([2j,4,6+3j])
print(arr.dtype)

complex128


# Array iterating

In [34]:
# it is mean to going through all elements inside array
arr = np.array([1,2,3,4,5])
for x in arr:
  print(x)

1
2
3
4
5


In [35]:
#if we want to do that for multi dimentional arry we use nditer()
arr = np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6


In [36]:
# ndenumerate() use it to give index and value of the element we want to access
arr = np.array([[1,2,3],[4,5,6]])
for x,y in np.ndenumerate(arr):
  print(x,y)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [37]:
# concatenate() use to joining two array
arr0 = np.arange(5)
arr1 = np.ones(6)
print(np.concatenate((arr0,arr1)))

[0. 1. 2. 3. 4. 1. 1. 1. 1. 1. 1.]


In [38]:
# concatenate() with 2D array (axis 0)
arr0 = np.array([[1,2,3],[5,6,7]])
arr1 = np.array([[8,9,10],[15,16,17]])
print(np.concatenate((arr0,arr1),axis=0))

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [15 16 17]]


In [39]:
# concatenate() with 2D array (axis 1)
arr0 = np.array([[1,2,3],[5,6,7]])
arr1 = np.array([[8,9,10],[15,16,17]])
print(np.concatenate((arr0,arr1),axis=1))

[[ 1  2  3  8  9 10]
 [ 5  6  7 15 16 17]]


# Spliting array

In [40]:
# array_split(array,number of pieces) use to split an array
arr = np.array([3,5,7,8,9,32])
narr = np.array_split(arr,4)
print("array after spliting :",narr,"\n")
print("index zero of new array : ",narr[0])

array after spliting : [array([3, 5]), array([7, 8]), array([9]), array([32])] 

index zero of new array :  [3 5]


In [42]:
# split 2D array
arr = np.array([[1,2,3],[5,6,7]])
narr = np.array_split(arr,4,axis=1)
print("array after spliting :",narr,"\n")
print("index zero of new array :\n ",narr[0])

array after spliting : [array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([], shape=(2, 0), dtype=int64)] 

index zero of new array :
  [[1]
 [5]]


# Searching in array

In [43]:
# we use where(condition) to search element inside array it is return the index of the value
arr = np.array([12,32,63,64,95])
y = np.where(arr == 12)
x = np.where(arr%2 == 0)
print(y)
print(x)

(array([0]),)
(array([0, 1, 3]),)


In [44]:
# searchsorted() use to search sorted array
arr = ([3,5,7,9,10])
x = np.searchsorted(arr,10)
print(x)

4


# sort array

In [45]:
# sort(array) use to sort array 1D
arr = np.array([3,8,4,6,2,1])
print(np.sort(arr))

[1 2 3 4 6 8]


In [46]:
# 2D sort
arr = np.array([[19,12,3],[51,16,27]])
print(np.sort(arr))

[[ 3 12 19]
 [16 27 51]]


# **Universal Functions (ufunc)**
# Arithmetic ufunc

In [47]:
# add()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("additon\n",np.add(arr0,arr1))

additon
 [[ 2  4  6  8]
 [10 12 14 16]]


In [ ]:
# subtract()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("subtraction\n",np.subtract(arr0,arr1))

subtraction
 [[0 0 0 0]
 [0 0 0 0]]


In [ ]:
# multiply()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("multiplcation\n",np.multiply(arr0,arr1))

multiplcation
 [[ 1  4  9 16]
 [25 36 49 64]]


In [ ]:
# divide()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("division\n",np.divide(arr0,arr1))

division
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# power()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("power\n",np.power(arr0,arr1))

power
 [[       1        4       27      256]
 [    3125    46656   823543 16777216]]


In [ ]:
# mod()
arr0 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print("reminder\n",np.mod(arr0,arr1))

reminder
 [[0 0 0 0]
 [0 0 0 0]]


# Statistical Functions

In [ ]:
# min() & max() use to show minimum and maximum value
arr = np.array([[19,12,3],[51,16,27]])
print("minimum = ",np.min(arr))
print("maximum = ",np.max(arr))

minimum =  3
maximum =  51


In [ ]:
# mean() sum of datasetes divide the numbers of them
arr = np.array([[19,12,3],[51,16,27]])
print("mean = ",np.mean(arr))

mean =  21.333333333333332


In [ ]:
# median() the middle number in a sorted ascending or descending list of numbers
arr = np.array([[19,12,3],[51,16,27]])
print("median = ",np.median(arr))

mean =  17.5


In [ ]:
# std() the average amount of variability in dataset
arr = np.array([[19,12,3],[51,16,27]])
print("standard deviation  = ",np.std(arr))

standard deviation  =  15.107025591499546


# Rounding

In [ ]:
# trunc() use to remove the part after point
arr = np.trunc([1.34,5.67,3.12])
arr

array([1., 5., 3.])

In [ ]:
# around() when the number is  => 5 it will be rounde to the bigger number else it will keep as same
arr = np.around([1.34,5.67,3.12])
arr

array([1., 6., 3.])

In [ ]:
# floor() use to round number to nearest lower number
arr = np.floor([1.34,5.67,3.12])
arr

array([1., 5., 3.])

In [ ]:
# ceil() use to round number to nearest greater number
arr = np.ceil([1.34,5.67,3.12])
arr

array([2., 6., 4.])